apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Cassandra Operator for Kubernetes by Instaclustr
home: https://www.instaclustr.com
sources:
  - https://github.com/instaclustr/cassandra-operator
keywords:
  - operator
  - cassandra-operator
  - instaclustr
maintainers:
  - name: Stefan Miklosovic
  - name: Alex Lourie
  - name: Ben Bromhead
  - name: Adam Zegelin
name: cassandra-operator
version: 1.1.5
