apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandradatacenters.cassandraoperator.instaclustr.com
spec:
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraDataCenter
    listKind: CassandraDataCenterList
    plural: cassandradatacenters
    singular: cassandradatacenter
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cassandraImage:
              type: string
            cluster:
              description: Cluster is either a string or v1.LocalObjectReference Cluster
                interface{} `json:"cluster,omitempty"`
              type: string
            dataVolumeClaimSpec:
              type: object
            imagePullPolicy:
              type: string
            imagePullSecrets:
              items:
                type: object
              type: array
            nodes:
              format: int32
              type: integer
            prometheusSupport:
              type: boolean
            resources:
              type: object
            sidecarImage:
              type: string
          required:
          - nodes
          - cassandraImage
          - sidecarImage
          - imagePullPolicy
          - resources
          - dataVolumeClaimSpec
          - prometheusSupport
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
