apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-operator-default-config
data:
  nodes: "3"
  cassandraImage: gcr.io/cassandra-operator/cassandra-3.11.6:latest
  sidecarImage: gcr.io/cassandra-operator/cassandra-sidecar:latest
  memory: 1Gi
  disk: 1Gi
  diskMedium: ""
