---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandrabackups.cassandraoperator.instaclustr.com
spec:
  additionalPrinterColumns:
  - JSONPath: .globalStatus
    description: Backup operation status
    name: Status
    type: string
  - JSONPath: .globalProgress
    description: Backup operation progress
    name: Progress
    type: string
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraBackup
    listKind: CassandraBackupList
    plural: cassandrabackups
    singular: cassandrabackup
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        globalProgress:
          type: string
        globalStatus:
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bandwidth:
              type: string
            cdc:
              description: Cassandra DC name to back up. Used to find the pods in
                the CDC
              type: string
            concurrentConnections:
              format: int64
              type: integer
            duration:
              type: string
            keyspaces:
              description: The list of keyspaces to back up
              items:
                type: string
              type: array
            snapshotTag:
              description: The snapshot tag for the backup
              type: string
            storageLocation:
              description: The uri for the backup target location e.g. s3 bucket,
                filepath
              type: string
            table:
              type: string
          required:
          - cdc
          - storageLocation
          - snapshotTag
          type: object
        status:
          items:
            properties:
              node:
                description: name of pod / node
                type: string
              progress:
                description: Progress shows the percentage of the operation done
                type: string
              state:
                description: State shows the status of the operation
                type: string
            required:
            - node
            - state
            - progress
            type: object
          type: array
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandraclusters.cassandraoperator.instaclustr.com
spec:
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraCluster
    listKind: CassandraClusterList
    plural: cassandraclusters
    singular: cassandracluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandradatacenters.cassandraoperator.instaclustr.com
spec:
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraDataCenter
    listKind: CassandraDataCenterList
    plural: cassandradatacenters
    singular: cassandradatacenter
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupSecretVolumeSource:
              type: object
            cassandraEnv:
              items:
                type: object
              type: array
            cassandraImage:
              type: string
            dataVolumeClaimSpec:
              type: object
            deletePVCs:
              type: boolean
            dummyVolume:
              type: object
            fsGroup:
              format: int64
              type: integer
            imagePullPolicy:
              type: string
            imagePullSecrets:
              items:
                type: object
              type: array
            nodes:
              format: int32
              type: integer
            optimizeKernelParams:
              type: boolean
            prometheusServiceMonitorLabels:
              additionalProperties:
                type: string
              type: object
            prometheusSupport:
              type: boolean
            racks:
              items:
                properties:
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  name:
                    type: string
                required:
                - name
                - labels
                type: object
              type: array
            resources:
              type: object
            restoreFromBackup:
              type: string
            serviceAccountName:
              type: string
            sidecarEnv:
              items:
                type: object
              type: array
            sidecarImage:
              type: string
            sidecarResources:
              type: object
            userConfigMapVolumeSource:
              type: object
            userSecretVolumeSource:
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
