# Default values for cassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride: test-dc-cassandra

image:
# Dev images
#  cassandraRepository: cassandra
#  sidecarRepository: cassandra-sidecar

# Published images
  cassandraRepository: gcr.io/cassandra-operator/cassandra-3.11.5
  sidecarRepository: gcr.io/cassandra-operator/cassandra-sidecar
  cassandraTag: latest
  sidecarTag: latest

imagePullPolicy: IfNotPresent
imagePullSecrets:
  - name: "regcred"

# Note these resource limits are not appropriate for production scenarios
# Generally require 8GB for JVM heap + more see https://github.com/apache/cassandra/blob/a145a485206f6a32b07979dfb1b983addf49dd10/conf/cassandra-env.sh#L17-L176

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi
#sidecarResources:
#  limits:
#    memory: 512Mi
#  requests:
#    memory: 512Mi
dataVolumeClaim:
  # Refer to doc/persistent_volumes.md for PV setup for dynamic volume provisioning
  # storageClassName: <topology-aware-standard>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# env properties for Cassandra container, similar to sidecarEnv
# cassandraEnv:

#racks:
#  - name: "west1-b"
#    labels:
#      failure-domain.beta.kubernetes.io/zone: europe-west1-b
#  - name: "west1-c"
#    labels:
#      failure-domain.beta.kubernetes.io/zone: europe-west1-c
#  - name: "west1-a"
#    labels:
#      failure-domain.beta.kubernetes.io/zone: europe-west1-a

#userConfigMapVolumeSource:
#  - name: configMapReference

#userSecretVolumeSource:
#  secretName: test-cassandra-dc-ssl

#sidecarSecretVolumeSource:
#  secretName: test-cassandra-dc-ssl-sidecar

#restore:
#  backupName: test-cassandra-backup-restore-s3
#  secret: cloud-backup-secrets

#optimizeKernelParams: true
prometheusEnabled: false
deletePVCs: false
passwordAuth: false