# Default values for cassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

fullnameOverride: test-dc-cassandra

image:
# Dev images
#  cassandraRepository: cassandra
#  sidecarRepository: cassandra-sidecar

# Published images
  cassandraRepository: gcr.io/cassandra-operator/cassandra-dev
  sidecarRepository: gcr.io/cassandra-operator/cassandra-sidecar-dev
  cassandraTag: 3.11.5
  sidecarTag: latest

imagePullPolicy: IfNotPresent
imagePullSecrets:
  - name: "regcred"

#optimizeKernelParams: true

# Note these resource limits are not appropriate for production scenarios
# Generally require 8GB for JVM heap + more see https://github.com/apache/cassandra/blob/a145a485206f6a32b07979dfb1b983addf49dd10/conf/cassandra-env.sh#L17-L176

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi
dataVolumeClaim:
  # Refer to doc/persistent_volumes.md for PV setup for dynamic volume provisioning
  # storageClassName: <topology-aware-standard>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

#sidecarEnv:
#  - name: GOOGLE_APPLICATION_CREDENTIALS
#    value: "/tmp/backup-creds/gcp.json"
#  - name: AWS_ACCESS_KEY_ID
#    valueFrom:
#      secretKeyRef:
#        name: backup-secrets
#        key: awsaccesskeyid
#  - name: AWS_SECRET_ACCESS_KEY
#    valueFrom:
#      secretKeyRef:
#        name: backup-secrets
#        key: awssecretaccesskey
#  - name: AWS_REGION
#    valueFrom:
#      secretKeyRef:
#        name: backup-secrets
#        key: awsregion
#  - name: AZURE_STORAGE_ACCOUNT
#    valueFrom:
#      secretKeyRef:
#        name: backup-secrets
#        key: azurestorageaccount
#  - name: AZURE_STORAGE_KEY
#    valueFrom:
#      secretKeyRef:
#        name: backup-secrets
#        key: azurestoragekey

# env properties for Cassandra container, similar to sidecarEnv
# cassandraEnv:

#backupSecretVolumeSource:
#  secretName: gcp-auth-reference
#  #   type is a workaround for https://github.com/kubernetes/kubernetes/issues/68466
#  type: array
#  items:
#    - key: gcp.json
#      path: gcp.json

#racks:
#  - name: "west1-b"
#    labels:
#      failure-domain.beta.kubernetes.io/zone: europe-west1-b
#  - name: "west1-c"
#    labels:
#      failure-domain.beta.kubernetes.io/zone: europe-west1-c
#  - name: "west1-a"
#    labels:
#      failure-domain.beta.kubernetes.io/zone: europe-west1-a

#userConfigMapVolumeSource:
#  - name: configMapReference

#restoreFromBackup: backup-name

# prometheusServiceMonitorLabels:
#  key: value
#  key2: value2
prometheusEnabled: false

#serviceAccountName: cassandra
